### ISSUE TITLE
Not working UI, can't test

### ISSUE THREAD

**Issue by e00dan** [esdras-santos/godex#1]
I tried to test the DEX on Godwoken as part of Nervos Gitcoin bounty but I can't get anything working. There are errors in the console.

<img width="1601" alt="image" src="https://user-images.githubusercontent.com/4950658/161256920-5a78e1a5-b38c-424c-a2c9-346ce1d741fe.png">
<img width="1771" alt="image" src="https://user-images.githubusercontent.com/4950658/161256983-12cf6f65-c2ac-4b6e-8d28-b7c1e2eefdf7.png">

**Comment by esdras-santos** [comment]
yes unfortunately I couldn't finish the UI in time

Enviado via e-mail seguro de [ProtonMail](https://protonmail.com/).

------- Original Message -------
Em sexta-feira, 1 de abril de 2022 às 08:44, Daniel Kmak ***@***.***> escreveu:
